#Docker Compose version being used
version: '3'
services:
  # Backend Service
  backend:
    
    #Builds the image from the Dockerfile located in the backend folder
    build: ./backend
    
    #Name of the Docker image, used for pushing and pulling on Docker Hub
    image: everestmc/backend 
    
    #Maps port 3001 in the container to port 3001 on my local machine
    ports: 
      - "3001:3001"
    
    #Organize volumes by:
    volumes:
      - ./backend:/app #Sync local backend folder with the containers directory in /app
      - backend_node_modules:/app/node_modules #Preserve node_module in a named volume so it isnt overwritten by accident
    
    #Leave this, this helps node.js know that there is something running in production
    environment:
      - NODE_ENV=production
    
    #Connect your backend to the network name created below
    networks:
      - app-network
  # Frontend Service
  #The comments above basically apply directly to everything happending in the front end
  frontend:
    
    build: ./frontend
    image: everestmc/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    # Leave this, this helps node.js know that there is something running in production
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--openssl-legacy-provider
    # This makes sure the front end looks for the backend
    depends_on:
      - backend
    # Connect your frontend to the network name created below
    networks:
      - app-network

#Defines persistent volumes used above to store folders
volumes:
  backend_node_modules:
  frontend_node_modules:

networks:
  app-network:
    driver: bridge
